export enum Languages {
    Javascript = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/1ac69ce5fbc389725f16f989fa53c62d6e1b4883/programming%20languages/javascript.svg",
    Typescript = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/1ac69ce5fbc389725f16f989fa53c62d6e1b4883/programming%20languages/typescript.svg",
    Spring = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/frameworks/spring.svg",
    PHP = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/1ac69ce5fbc389725f16f989fa53c62d6e1b4883/social%20icons/php.svg",
    NodeJS = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/1ac69ce5fbc389725f16f989fa53c62d6e1b4883/frameworks/nodejs.svg",
    BunJS = "https://bun.sh/logo.svg",
    JQuery = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/frameworks/jquery.svg",
    HTML = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/1ac69ce5fbc389725f16f989fa53c62d6e1b4883/social%20icons/html5.svg",
    CSS = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/1ac69ce5fbc389725f16f989fa53c62d6e1b4883/social%20icons/css3.svg",
    React = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/frameworks/react.svg",
    VueJS = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/frameworks/vuejs.svg",
    Angular = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/frameworks/angular.svg",
    ReactNative = "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
    Flutter = "https://upload.wikimedia.org/wikipedia/commons/4/44/Google-flutter-logo.svg",
    MongoDB = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/databases/mongodb.svg",
    MySQL = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/databases/mysql.svg",
    PostgresQL = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/databases/postgresql.svg",
    Csharp = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/programming%20languages/c%23.svg",
    Rust = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/programming%20languages/rust.svg",
    Java = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/programming%20languages/java.svg",
    Python = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/1ac69ce5fbc389725f16f989fa53c62d6e1b4883/programming%20languages/python.svg",
    Docker = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/cloud/docker.svg",
    Github = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/cloud/github.svg",
    AWS = "https://raw.githubusercontent.com/bablubambal/All_logo_and_pictures/main/cloud/amazon.svg",
    Notion = "https://upload.wikimedia.org/wikipedia/commons/e/e9/Notion-logo.svg"
}